const $=id=>document.getElementById(id);const screens=["home","camera","videoTest","profile"];let stream=null,bestCapture=null,captureSamples=[],scanTimer=null;
function show(n){screens.forEach(s=>$(s).classList.toggle("active",s===n))}
function luminance(r,g,b){return .2126*r+.7152*g+.0722*b}
function scoreCanvas(c){const x=c.getContext("2d",{willReadFrequently:true}),w=c.width,h=c.height,d=x.getImageData(0,0,w,h).data,step=4;let s=0,s2=0,n=0;for(let y=1;y<h-1;y+=step)for(let z=1;z<w-1;z+=step){let i=(y*w+z)*4,c=luminance(d[i],d[i+1],d[i+2]),l=luminance(d[i-4],d[i-3],d[i-2]),r=luminance(d[i+4],d[i+5],d[i+6]),u=luminance(d[i-w*4],d[i-w*4+1],d[i-w*4+2]),v=luminance(d[i+w*4],d[i+w*4+1],d[i+w*4+2]),q=Math.abs(4*c-l-r-u-v);s+=q;s2+=q*q;n++}return Math.min(100,Math.sqrt(Math.max(0,s2/n-(s/n)**2))*2.4)}
function drawVideo(v,c){let w=360,h=Math.round(360*(v.videoHeight/v.videoWidth||1));c.width=w;c.height=h;c.getContext("2d").drawImage(v,0,0,w,h)}
function cropCenter(v,c){let w=v.videoWidth||c.width,h=v.videoHeight||c.height;c.width=w;c.height=h;c.getContext("2d").drawImage(v,0,0,w,h);let sz=Math.min(w,h)*.58,x=(w-sz)/2,y=(h-sz)/2,o=document.createElement("canvas");o.width=o.height=640;o.getContext("2d").drawImage(c,x,y,sz,sz,0,0,640,640);return o.toDataURL("image/jpeg",.9)}
function setQ(q){$("qualityBar").style.width=q+"%";$("qualityText").textContent=q<25?"MOVE CLOSER":q<45?"HOLD STEADY":q<65?"GOOD":"EXCELLENT"}
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment",width:{ideal:1280},height:{ideal:720}},audio:false});$("video").srcObject=stream;await $("video").play();show("camera");loop()}catch(e){alert("Camera access needs HTTPS and permission. If opened as a local file, upload it to the HTTPS website first.")}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(scanTimer)cancelAnimationFrame(scanTimer);show("home")}
function loop(){const v=$("video"),c=$("frameCanvas");if(!v.videoWidth)return;drawVideo(v,c);let q=scoreCanvas(c);setQ(q);if(q>55){bestCapture={dataUrl:cropCenter(v,c),quality:q};$("instruction").textContent="Good. Hold for capture."}else $("instruction").textContent=q<25?"Move closer to the nose.":"Hold the phone steady.";scanTimer=requestAnimationFrame(loop)}
$("startCamera").onclick=startCamera;$("stopCamera").onclick=stopCamera;
$("captureNow").onclick=()=>{const v=$("video"),c=$("frameCanvas");if(!v.videoWidth)return;drawVideo(v,c);let q=scoreCanvas(c),img=cropCenter(v,c);captureSamples.push({dataUrl:img,quality:q});bestCapture={dataUrl:img,quality:q};$("frameCounter").textContent=captureSamples.length+" samples"};
$("finishScan").onclick=()=>{if(!bestCapture&&!captureSamples.length)return alert("No sample captured yet.");show("profile")};
$("profileBack").onclick=()=>show("camera");
$("saveProfile").onclick=()=>{let name=$("catName").value.trim()||"Unknown Cat",s=bestCapture||captureSamples.at(-1),r={id:"cat_"+Date.now(),name,nickname:$("catNickname").value.trim(),createdAt:new Date().toISOString(),sample:s,samples:captureSamples};localStorage.setItem("catNosePrototype_last",JSON.stringify(r));$("savedInfo").classList.remove("hidden");$("savedInfo").innerHTML="<h3>🐱 "+name+"</h3><p><b>NOSE SAMPLE SAVED</b></p><p>This v0.1 does not yet perform biometric recognition. The image is stored locally as a test sample.</p><img src='"+s.dataUrl+"' style='width:100%;border-radius:16px'>"};
$("backHome").onclick=()=>show("home");
$("mediaInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;if(f.type.startsWith("image/")){let u=URL.createObjectURL(f),im=new Image;im.onload=()=>{let c=$("videoCanvas");c.width=im.naturalWidth;c.height=im.naturalHeight;c.getContext("2d").drawImage(im,0,0);let q=scoreCanvas(c);$("videoQuality").textContent=Math.round(q)+"%";$("videoQualityBar").style.width=Math.min(100,q)+"%";$("videoResult").classList.remove("hidden");$("videoResult").innerHTML="<b>IMAGE TEST</b><p>Generic image-quality score: "+Math.round(q)+". Not nose recognition.</p><img src='"+u+"' style='width:100%;border-radius:14px'>";show("videoTest")};im.src=u}else{$("sourceVideo").src=URL.createObjectURL(f);show("videoTest")}};
$("analyzeVideo").onclick=async()=>{let v=$("sourceVideo");if(!v.duration)return alert("Choose a video first.");let c=$("videoCanvas"),a=[],N=Math.min(30,Math.max(12,Math.floor(v.duration*2)));for(let i=0;i<N;i++){v.currentTime=v.duration*i/(N-1);await new Promise(r=>v.onseeked=r);drawVideo(v,c);let q=scoreCanvas(c);a.push({q,img:cropCenter(v,c)})}a.sort((x,y)=>y.q-x.q);let best=a.slice(0,9);$("videoQuality").textContent=Math.round(best[0].q)+"%";$("videoQualityBar").style.width=Math.min(100,best[0].q)+"%";$("videoResult").classList.remove("hidden");$("videoResult").innerHTML="<b>VIDEO ANALYSIS COMPLETE</b><p>Sampled "+N+" frames. Best generic quality score: "+Math.round(best[0].q)+".</p><p><b>Important:</b> the current prototype crops the central scan zone; a dedicated nose detector comes next.</p>";$("videoSamples").innerHTML=best.map(x=>"<img src='"+x.img+"'>").join("")};
